# core/strings.py
from typing import Any

STRINGS: dict[str, dict[str, Any]] = {
  'en-US': {
    'main.continue':'Continue',
    'main.options':['Campaign','Settings','Exit'],
    'campaign.options':['New Game','Load Game','Delete Game','Back'],
    'saves.title.load':'Load Game','saves.title.delete':'Delete Game','saves.title.save':'Save Game',
    'saves.hint':'ENTER to select • ESC back','saves.slot':'Slot','saves.available':'Available','saves.empty':'Empty','saves.deleted':'Deleted.',
    'settings.title':'Settings','settings.back':'Back','settings.show_missing':'Show Missing Overlay',
    'settings.resolution':'Resolution','settings.scale_mode':'Scale Mode','settings.scale_mode.values':['Fit','Cover'],
    'settings.fx_bloom':'Bloom (Lite)','settings.fx_dof':'Depth of Field (Lite)',
    'settings.fx_quality':'FX Buffer','settings.fx_quality.values':['Half','Quarter'],
    'settings.fps':'FPS','settings.audio':'Audio','settings.mute':'Mute',
    'settings.difficulty':'Difficulty','settings.controls':'Controls','settings.language':'Language',
    'settings.lang.values':['English (US)','Português (Brasil)'],

    'charv2.titles': ['Identity','Lineage','Vocation','Star Sign','Skills (Pick 2)','Name','Summary'],
    'charv2.gender': 'Gender',
    'charv2.gender.desc': 'Select the character gender. This choice is cosmetic and affects portraits.',
    'charv2.skills': 'Skills',
    'charv2.name': 'Name',
    'charv2.hint.nav': '←/→ to change • ENTER confirm • ESC back',
    'charv2.hint.skills': '←/→ navigate • ENTER select/deselect • Need 2 skills • ESC back',
    'charv2.hint.name': 'ENTER confirm • ESC back',
    'charv2.hint.summary': 'ENTER to start • ESC to edit',
    'charv2.summary.name': 'Name',
    'charv2.summary.gender': 'Gender',
    'charv2.summary.race': 'Race',
    'charv2.summary.class': 'Class',
    'charv2.summary.sign': 'Sign',
    'charv2.summary.skills': 'Skills',
    'charv2.summary.attributes': 'Final Attributes',
    'charv2.summary.derived': 'Derived Stats',
  },
  'pt-BR': {
    'main.continue':'Continuar',
    'main.options':['Campanha','Configurações','Sair'],
    'campaign.options':['Novo Jogo','Carregar Jogo','Excluir Jogo','Voltar'],
    'saves.title.load':'Carregar Jogo','saves.title.delete':'Excluir Jogo','saves.title.save':'Salvar Jogo',
    'saves.hint':'ENTER seleciona • ESC volta','saves.slot':'Slot','saves.available':'Disponível','saves.empty':'Vazio','saves.deleted':'Excluído.',
    'settings.title':'Configurações','settings.back':'Voltar','settings.show_missing':'Mostrar Aviso de Assets Ausentes',
    'settings.resolution':'Resolução','settings.scale_mode':'Modo de Escala','settings.scale_mode.values':['Ajustar','Cobrir'],
    'settings.fx_bloom':'Bloom (Leve)','settings.fx_dof':'Profundidade de Campo (Leve)',
    'settings.fx_quality':'Buffer de FX','settings.fx_quality.values':['Metade','Quarto'],
    'settings.fps':'FPS','settings.audio':'Áudio','settings.mute':'Mudo',
    'settings.difficulty':'Dificuldade','settings.controls':'Controles','settings.language':'Idioma',
    'settings.lang.values':['English (US)','Português (Brasil)'],

    'charv2.titles': ['Identidade','Linhagem','Vocação','Signo Astral','Perícias (Escolha 2)','Nome','Resumo'],
    'charv2.gender': 'Gênero',
    'charv2.gender.desc': 'Selecione o gênero do personagem. Esta escolha é cosmética e afeta os retratos.',
    'charv2.skills': 'Perícias',
    'charv2.name': 'Nome',
    'charv2.hint.nav': '←/→ altera • ENTER confirma • ESC volta',
    'charv2.hint.skills': '←/→ navega • ENTER seleciona/deseleciona • Precisa de 2 • ESC volta',
    'charv2.hint.name': 'ENTER confirma • ESC volta',
    'charv2.hint.summary': 'ENTER inicia • ESC edita',
    'charv2.summary.name': 'Nome',
    'charv2.summary.gender': 'Gênero',
    'charv2.summary.race': 'Raça',
    'charv2.summary.class': 'Classe',
    'charv2.summary.sign': 'Constelação',
    'charv2.summary.skills': 'Perícias',
    'charv2.summary.attributes': 'Atributos Finais',
    'charv2.summary.derived': 'Atributos Derivados',
  }
}

def t(key: str, lang: str = 'en-US'):
    return STRINGS.get(lang, {}).get(key, STRINGS.get('en-US', {}).get(key, key))
